### ISSUE TITLE
how to redirect to "next" after login?

### ISSUE THREAD

**Issue by doctsh** [shubhamdipt/django-microsoft-authentication#6]
Hi
Thanks for the nice package.
Now after signing in successfully, it goes to /accounts/profile. instead how to make it to go to originally visited page before login (next)?

**Comment by shubhamdipt** [comment]
LOGIN_URL = "/microsoft_authentication/login"
LOGIN_REDIRECT_URL = "/admin"  # optional and can be changed to any other url

**Comment by shubhamdipt** [comment]
Added in new version
