### ISSUE TITLE
Populate user name fields in Django users from Azure AD

### ISSUE THREAD

**Issue by twillisCFB** [shubhamdipt/django-microsoft-authentication#9]
Is it possible to populate the first and last name fields in Django from the users Azure AD name?

Is there a way to ensure new Django users are not automatically made staff members on the site?

**Comment by shubhamdipt** [comment]
Thanks for pointing this out. A new version has been released with new commits.

[ref: ](https://github.com/shubhamdipt/django-microsoft-authentication/blob/master/README.md?plain=1#L48)

**Comment by gelie** [comment]
I added two new fields for the last_name and first_name (auth_utils.py):
`--def get_django_user(email, create_new=True, is_staff=True):`
`++def get_django_user(email, create_new=True, is_staff=True, first_name="", last_name=""):`

And then in the callback funtion in views.py:
`user = get_django_user(email=ms_user.get("mail") or ms_user.get("userPrincipalName"), first_name=ms_user.get("givenName"), last_name=ms_user.get("surname"))`

It is a quick and dirty hack. Maybe it will be included in the next version.
